### ISSUE TITLE
Formulário com agrupamento fake

### ISSUE THREAD

**Issue by fabrycyocarvalho** [tributus/RZFormWidget#4]
Quando o primeiro campo do formulário é um fieldgroup esta tendo o seguinte comportamento.
![default - google chrome](https://cloud.githubusercontent.com/assets/5272057/16820264/94a1613e-4926-11e6-851e-bb1e995cece6.jpg)

**Comment by fabrycyocarvalho** [comment]
Previsão para corrigir esse bug?

**Comment by tributus** [comment]
será liberado no próximo release
